version: "3.4"

services:
    nginx:
        image: nginx:alpine
        ports:
          - "4000:90"
        volumes:
          - ./out:/usr/share/nginx/html
          - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - api

    api:
        build:
          context: .
          dockerfile: dockerfile
        ports:
          - "5048:80"
        # volumes:
        #   - .:/app
        depends_on:
          - db

    db:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        ports:
          - "1433:1433"
        environment:
            SA_PASSWORD: "Lapo_dev6$"
            ACCEPT_EULA: "Y"